language: go
sudo: false
services:
  - redis-server

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get -v github.com/garyburd/redigo/redis
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN